application: team-player
version: 1-1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- admin_redirect: on



handlers:

- url: /assets
  static_dir: assets
  
- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico

- url: /admin/.*
  script: main.app
  login: admin

- url: .*
  script: main.app
